# permissions for end users to view ironicdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ironicdatabase-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ironic-standalone-operator
    app.kubernetes.io/part-of: ironic-standalone-operator
    app.kubernetes.io/managed-by: kustomize
  name: ironicdatabase-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - ironicdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - ironicdatabases/status
  verbs:
  - get
