name: Functional

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: helm/kind-action@v1
      with:
        cluster_name: kind
    - name: Prepare tests
      run: LOGDIR=/tmp/logs ./test/prepare.sh
    - name: Run tests
      run: |
        cd test
        LOGDIR=/tmp/logs go test -timeout 60m
    - name: Collect logs
      run: LOGDIR=/tmp/logs ./test/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functional
        path: /tmp/logs/*
      if: always()
