name: Functional

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: helm/kind-action@v1
      with:
        cluster_name: kind
    - name: Prepare tests
      run: ./test/prepare.sh
    - name: Run tests
      run: cd test && go test -timeout 60m
    # TODO(dtantsur): turn this into a normal artifact collection
    - name: Show any local logs
      run: cat test/*.log
      if: always()
    - name: Show the deployment
      run: kubectl get -o yaml -n ironic-standalone-operator-system deployment/ironic-standalone-operator-controller-manager
      if: always()
    - name: Show all pods
      run: kubectl get -o yaml -n ironic-standalone-operator-system pod
      if: always()
    - name: Show the logs
      run: kubectl logs -n ironic-standalone-operator-system deployment/ironic-standalone-operator-controller-manager
      if: always()
    - name: Show all Ironic objects
      run: kubectl get -o yaml -A ironic
      if: always()
